# Generated by Django 5.1.1 on 2024-09-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productUrl', models.CharField(max_length=300)),
                ('producttitle', models.CharField(max_length=100)),
                ('productDescription', models.CharField(max_length=400)),
                ('productPrice', models.CharField(max_length=100)),
            ],
        ),
    ]
