# Generated by Django 5.1.1 on 2024-10-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
