# Generated by Django 5.1.1 on 2024-10-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productsmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
